### ISSUE TITLE
AtagOne Outside Temp -100.0 °C

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#10]
ik krijg tegenwoordig geen outside temp meer door... Jullie ook?

**Comment by herikw** [comment]
Hetzelfde hier. In de atag one app in diagnose ook  "Niet beschikbaar". Dit betekent waarschijnlijk ook dat de temperatuur afhankelijke mode waar mijn thermostaat in staat niet zal werken zoals het hoort. Volgens mij is dit geen sensor, maar een weerdienst.

**Comment by herikw** [comment]
Volgens de documentatie moet bij de weersafhankelijk mode de optie "Ruimte Invloed"  op "uit" staan. Na deze gezet te hebben zie ik weer een buitentemperatuur.

**Comment by RezzZ** [comment]
ik heb mijn cv niet eens in weer mode staan. CV stond continu te verwarmen al was het minimaal toen ik die aanzette. Niet wat ik wilde dus heb hem er vanaf gehaald. sindsdien geen buitentemperatuur meer.
Ik heb je instructies opgevolgd door even de weermode aan te zetten en ruimte invloed op uit (stond ie al) en ik zie wel een temp in de app van atagone bij diagnosis (geen idee of daar ook -100 stond of niet beschikbaar zoals bij jou). Ik ga HA eens opnieuw opstarten. misschien krijg ik daarna weer een temp door, maar belangrijk is het niet (heb toch al een buienradar component in HA)

**Comment by daranto** [comment]
Hello, 

I have the same problem. As you can see in this picture sometimes the temp drops to -100:

https://imgur.com/a/IrtDTq8

Daranto
