### ISSUE TITLE
Home assitant 0.96 compatability

### ISSUE THREAD

**Issue by reharmsen** [herikw/home-assistant-custom-components#13]
With Home Assistant 0.96 the Climate integration has changed.
Will this custom component be updated?

See here for details: https://www.home-assistant.io/blog/2019/07/17/release-96/#climate

**Comment by petreef** [comment]
Same problem here I’m missing the thermostat

**Comment by herikw** [comment]
They changed the Climate Core Component and there is no backward compatibility so I'm updating the Atag One climate component. I hope to have it available in the coming days.

**Comment by RezzZ** [comment]
any update? @herikw

**Comment by herikw** [comment]
The latest version with the fixes are made available some time ago and ready to download

**Comment by reharmsen** [comment]
Was fixed some time ago
