### ISSUE TITLE
Retry during component initialization

### ISSUE THREAD

**Issue by TheNr1Guest** [herikw/home-assistant-custom-components#14]
My Atag One has an unstable wifi connection, this results in the component being unavailable during start up. Sometimes multiple restarts of Home Assistant are being required to resolve this. I was wondering, could a simple retry mechanism be implemented where the default is 1 and we can set a custom retry count to ensure a higher chance of the component being loaded after a Home Assistant restart?

**Comment by TheNr1Guest** [comment]
I could not resist checking the code myself. I found that a retry mechanism would not be ideal. What did work was changing some error handling for which I have submitted a pull request: https://github.com/herikw/home-assistant-custom-components/pull/15

**Comment by herikw** [comment]
There is a new release that contains support for dynamic IP address and has an improved retry mechanism. Give it a try.
