### ISSUE TITLE
Add repository to default HACS list

### ISSUE THREAD

**Issue by reharmsen** [herikw/home-assistant-custom-components#17]
On order to add the component to the default HACS repository, the maintainer has to file a pull request at the data branch of HACS.

Specifically in this file a new line needs to be added:
https://github.com/custom-components/hacs/blob/data/repositories/plugin
"herikw/home-assistant-custom-components"

This would fully complete #16

**Comment by herikw** [comment]
Changes has been approved by the hacs-bot. So it should be listed in the default repository soon.

**Comment by herikw** [comment]
I can confirm that the Atag One custom component is now in the default repository of HACS.
