### ISSUE TITLE
Component not loaded

### ISSUE THREAD

**Issue by pasqui7** [herikw/home-assistant-custom-components#19]
Hi guys,
I've tried to install this component, 
but when I restart home assistant came out one error message:

Platform error climate.atagone - Integration 'atagone' not found.

Can you help me?

Thanks

**Comment by RezzZ** [comment]
how did you install? Did you manually install? or did you use HACS? If not, HACS could be a nice option. Auto install and easy updatable without ssh.

**Comment by pasqui7** [comment]
Not yet with HACS. I need to understand how can I install it in home assistant before try. 

Can you explain me ?

**Comment by RezzZ** [comment]
how to install hacs? you can find it on the page of HACS:
https://community.home-assistant.io/t/custom-component-hacs/121727
https://hacs.netlify.com/docs/installation/manual

**Comment by pasqui7** [comment]
Many thanks! I need to try. 
I came back in Monday

**Comment by pasqui7** [comment]
Hi RezzZ,
I installed HACS, but it is impossible to install any integration. 

When I try to search the Atag integration, I can see it, but the "Install" button it is grey out, and also for all of other integrations .

![Schermata 2019-12-15 alle 00 13 16](https://user-images.githubusercontent.com/37555547/70855725-de9b3a80-1ecf-11ea-8d43-374d1f8a0337.png)

Can you help me?

thanks

**Comment by RezzZ** [comment]
@pasqui7 what version of HA are you running?

**Comment by pasqui7** [comment]
0.103.0

**Comment by RezzZ** [comment]
did you check the pre-reqs part of the installation of HACS?
