### ISSUE TITLE
Atag ONE Mode

### ISSUE THREAD

**Issue by Bergerie** [herikw/home-assistant-custom-components#21]
The Atag One has an Automatic, Vacation, Manual, Extend & Fireplace mode. However, the loaded version from the HAC store only allows the selection of an HEAT mode. Is this as it is, or have I potentially done something wrong which caused this inconsistency.

**Comment by RezzZ** [comment]
heat and off are the only modes the build-in Thermostat Climate component in HA knows unfortunately. So you did nothing wrong ;)

**Comment by herikw** [comment]
I'm currently working on a new version that supports the different operation modes. Vacation will be supported through new services that can be called using an automation. I hope to finish and release this week.

**Comment by herikw** [comment]
New version supports some of the modes as displayed in the Atag One App. Home = Auto, Away = Manual and Vacation, which is set automatically when a schedule has been set using the new Vacation Services.
