### ISSUE TITLE
Question: breaking changes headup?

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#22]
just updated to latest version but would have been nice if you informed us about the rename of the component 😉 

had to adjust all my automations.

Haven't tried the vacation mode yet as i build one myself but will try it at some point. Keep up the great work!

**Comment by herikw** [comment]
Hi Rezz, Yes you are right, I didn't realize since I'm using the Name in the platform properties. So, for me this was already the name I was using.

**Comment by RezzZ** [comment]
@herikw Name in the platform properties? Not sure what you mean with that. Is there a different way to track changes for the climate component than by entity name? Can you share an example?
I’m switching to nodered in the future but i need to overcome a few problems first before I can do that.
