### ISSUE TITLE
ClimateDevice is deprecated, modify AtagOneThermostat to extend ClimateEntity

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#25]
New HA 110.1 introduced some updates for the climate component marking this atagone component as deprecated

```
Logger: homeassistant.components.climate
Source: components/climate/__init__.py:547
Integration: Climate (documentation, issues)
First occurred: 2:05:50 AM (1 occurrences)
Last logged: 2:05:50 AM

ClimateDevice is deprecated, modify AtagOneThermostat to extend ClimateEntity
```

**Comment by plutosherry** [comment]
me too ...... display the same alarm

**Comment by herikw** [comment]
I just released a new version with a fix for this issue. It should not longer be reported in the logs.
Please note that the "Detected I/O inside the event loop" is still there. This also needs some changes in the code. A lot is changed in the Core of Homeassistant in the latest release(s). One of the things is this I/O detection warning.

**Comment by reharmsen** [comment]
You might want to consider using the 'official' component that is offered in the Core that was introduced with 0.109: https://www.home-assistant.io/integrations/atag/

And perhaps suggest changes when you are missing features.
