### ISSUE TITLE
atag one doesnot work

### ISSUE THREAD

**Issue by rene-72** [herikw/home-assistant-custom-components#27]
Installed the atag one then entered the ip address it shows it has been found but when I look into the integrations it shows a red border with 2 lines of text 

naamloze invoer with red exclamation mark
naamloze invoer with red exclamation mark

Did restart home assistant a few times, also removed and reinstalled but no success my atag one android app can connect to my atag one without an issue.

**Comment by herikw** [comment]
Are you running a recent version of Home Assistant?  (for instance 2022.2.0....)
Otherwise can you have a look at the log to see what's going on. It should display something similar to the following screen:

![image](https://user-images.githubusercontent.com/13335441/149624966-892effa8-3675-4db7-80e4-0adac6fdaad4.png)

**Comment by rene-72** [comment]
Hi it took long but it shows data now.  But my p1 meter is not working another issue. Using the latest ha.
But will look into this running on rasberry pi 3b+ but will move to raspberry 4 because ha is not very fast :-(

**Comment by herikw** [comment]
Don't know what happened to the energy tab but it seems to be removed in the latest development branches. However it's still there in the stable 2021.12.9 release. Maybe you should give that a try?

**Comment by rene-72** [comment]
I got issues with home assistant waiting for my micro hdmi so I can try on a pi 4b 2gb that has 1gb more then the 3b+ and should run better.
The 8gb is in backorder. I will test some more but It seems when I start working with zwave-js the atag one stops working. zwave-js2mqtt makes it even worse it makes mij HA unresponsive 😟

**Comment by rene-72** [comment]
I do have the energy tab in the hasio version I run 2021-12-9 core and 2021-12-2 supervisor
