### ISSUE TITLE
Atag One is unavailable

### ISSUE THREAD

**Issue by ghost** [herikw/home-assistant-custom-components#29]
I have successfully added the HACS integration into HA. The Atag One however doesn't become available.
The IP address is correct and the port used is 10000. Any idea why this happens?

![Screenshot 2022-10-26 at 10 25 33](https://user-images.githubusercontent.com/56460611/197974583-db87ecd0-9577-4a4d-922f-90bac83148d2.png)
![Screenshot 2022-10-26 at 10 24 52](https://user-images.githubusercontent.com/56460611/197974590-e51a0769-9f06-4429-af83-dbee207f3642.png)

**Comment by herikw** [comment]
There seems to be a issue with the communication to your Atag device. Can you check the log file to see what's going on?
Btw. you configured the IP address and port in the GUI?

**Comment by ghost** [comment]
Thanks. I found out that there is a difference between an Atag One and Atag One zone. I have it working with Apple Home - Kit but not that many metrics to draw fancy graphs from. I think to buy just a One and sell my One Zone.
