### ISSUE TITLE
async_setup_platforms

### ISSUE THREAD

**Issue by FutureCow** [herikw/home-assistant-custom-components#30]
I'm using this component for quite some while, but looking at the logs, found that there is a problem with the async_setup. The next version of HA (2023.3) will not support async_setup_platforms, but is using async_forward_entry_setups.
Can you update this intergration?

> Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for atagone using this method at custom_components/atagone/__init__.py, line 62: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

Also got this error:

> Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2023.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for average using this method at custom_components/average/sensor.py, line 258: temperature = convert_temperature(float(temperature), entity_unit, ha_unit)

**Comment by herikw** [comment]
Hi FutureCow, Let me investigate and update. Thanks for reporting!
I will report back once updated....

**Comment by herikw** [comment]
Atag Custom Component has been updated. (v2.0.2). 

The second error that you have is from another Custom Component called Average. You need to contact the owner to fix the issue with temperature
