### ISSUE TITLE
enable all sensors?

### ISSUE THREAD

**Issue by jcoetsie** [herikw/home-assistant-custom-components#4]
Hi,

First of all thanks for your great work.

Would it be possible to expose all sensor data that is available through the api?

    "deviceIP": "192.168.50.65",
    "deviceId": "6808-1700-2002_18-15-002-390",
    "latestReportTime": "2018-09-22 14:23:29",
    "burningHours": 1.06,
    "roomTemperature": 21.2,
    "outsideTemperature": 12.0,
    "dhwSetpoint": 60.0,
    "dhwWaterTemperature": 54.0,
    "chSetpoint": 0.0,
    "chWaterTemperature": 21.2,
    "chWaterPressure": 1.1,
    "chReturnTemperature": 21.2,
    "targetTemperature": 21.0,
    "deviceStatus": 1,
    "connectionStatus": 23,
    "deviceErrors": "",
    "boilerErrors": "",
    "dbgOutsideTemp": 24.3,
    "pcbTemp": 27.9,
    "dhwWaterTemp": 54.0,
    "dhwWaterPres": 0.0,
    "boilerStatus": 512,
    "boilerConfig": 258,
    "chTimeToTemp": 0,
    "powerCons": 0,
    "rssi": 49,
    "current": 12,
    "voltage": 3774,
    "resets": 1,
    "memoryAllocation": 2800,
    "chStatus": 33,
    "chControl_mode": 0,
    "chMode": 2,
    "chModeDuration": 0,
    "chModeTemp": 21.0,
    "dhwStatus": 53,
    "dhwMode": 1,
    "weatherTemp": 11.9,
    "weatherStatus": 2,
    "vacationDuration": 0,
    "extendDuration": 0,
    "fireplaceDuration": 10800,
    "flameStatus": "Off",
    "atagOneVersion": "R56",
    "macAddress": "78-4F-43-51-2E-E6"

**Comment by herikw** [comment]
I have added a couple of extra sensors. If looking at my own configuration these are the fields that seems to have some usable values.
Please let me know when there is a need for some other report field(s)

**Comment by jcoetsie** [comment]
Hi,

tx. Can never have enough sensors :-)

I use this to understand "de stooklijn" of the Atag.

I can't seem to be able to activate the sensors though.

I copied "atagone.py" to the config/custom_components/sensor

I see no errors. Should this file be elsewhere?

**Comment by jcoetsie** [comment]
I use hass.io btw

**Comment by RezzZ** [comment]
same here but that running HA on rpi3B+ inside docker.
I enabled the sensors but the don't show up..

**Comment by jcoetsie** [comment]
Rene,

The doc is nit clear on that but you need a separate  entry for the sensors:

I have this:

Main configuration.yaml

sensor: !include sensors.yaml

In sensors.yml

- platform: atagone
  host: <YOUR IP>
  port: 10000
  scan_interval: 10
  resources:
    - room_temp
    - outside_temp
    - avg_outside_temp
    - pcb_temp
    - ch_setpoint
    - ch_water_pressure
    - ch_water_temp
    - ch_return_temp
    - dhw_water_temp
    - dhw_water_pres
    - boiler_status
    - boiler_config

**Comment by RezzZ** [comment]
ahh I had that resources part in the climate setup. I removed it there, added a new atagone.yaml in my sensors folder. I now have all sensors present in HA. Thanks!

**Comment by pipetboy** [comment]
Hi!
Great work! This is adding a lot of intelligence into my ATAG One setup! (I now have geofencing!!! )
The only sensor I am still missing, however, is the target temperature. (I'd like to graph that)

Thank you so much!!
Theo

**Comment by RezzZ** [comment]
target temperature is already part of the climate.atagone_thermostat right? If you record it in influxdb I believe target temp should already be a part of it for you to graph?

Otherwise you can always create a template sensor based on the attribute "temperature" of the thermostat.

**Comment by pipetboy** [comment]
Sure you can add it with a template sensor, but it is kinda strange to have all these sensors (like room temp, water temp, outside temp, water pressure, etc) already included and then miss the target temp....

**Comment by RezzZ** [comment]
That’s true but target temp is not an actual sensor. It’s the temp you set in the thermostat component so, to me, it seems a bit redundant to add another sensor with the same value. besides, the climate component already graphs target and current temp so where are you exactly missing the option to graph the target temp? Do you want to do that in HA? Or are you using an external database like influx and grafana for displaying and dashboarding?

**Comment by sildehoop** [comment]
I would also like to have the target temp to use with the custom mini graph card

**Comment by pipetboy** [comment]
Slidehoop,

You will have to create the sensor yourself...

`  - platform: template
    sensors:
      target_temp:
        friendly_name: "Temperatuur instelling"
        entity_id: climate.atag_one_thermostat
        value_template: "{{ state_attr('climate.atag_one_thermostat', 'temperature') }}"
        unit_of_measurement: '°C'
        icon_template: mdi:thermostat-box`

Hope this helps...

**Comment by mmlaarhoven** [comment]
I also would like it very much to store the target temp in the influx db in a very easy way...

**Comment by RezzZ** [comment]
target temp is already part of the state attribute of your climate.atagone component. Just push that to influx and you can easily view your current and target temp in grafana.

a query in grafana could look something like this:
```
SELECT mean("temperature") AS "target temp", mean("current_temperature") AS "current temp" FROM "state" WHERE ("entity_id" = 'atagone_thermostat') AND $timeFilter GROUP BY time($__interval) fill(linear)
```
it would something like like this:
![image](https://user-images.githubusercontent.com/70499/74136031-abcea380-4bed-11ea-87bb-b63b132caff8.png)

**Comment by Bergerie** [comment]
I'm currently using the API to interface with Home assistant. In order to allow a 1 to 1 transfer to the custom component, I'm short of the following sensor data:
['retrieve_reply']['control']['ch_mode_temp']
['retrieve_reply']['control']['ch_control_mode']
['retrieve_reply']['control']['ch_mode']
['retrieve_reply']['configuration']['ch_heating_type']
['retrieve_reply']['wifi_scan']['ssid_list'][0]['SSID']
['retrieve_reply']['wifi_scan']['ssid_list'][0]['RSSI']
Would it be possible to include these. 
![Screenshot_2020-07-12 Overview - Home Assistant](https://user-images.githubusercontent.com/16453895/87242759-e3a57580-c42f-11ea-87d1-7cc278740f77.png)

**Comment by Bergerie** [comment]
Any thoughts about my request of 12th Juliy for incremental sensors? Would highly appreciate feedback whether possible.

**Comment by pmeij270769** [comment]
Hi there. I am fairly new to Home assistant and trying to find my way through various setups. 

Am trying to get the ATAG one working. I did the setup and entities now shows the Atag One as climate.atag_one. Copying sensor section into configuration.yaml and restarting however does not add sensor entities. Am I missing a step.

**Comment by Bergerie** [comment]
Doubt whether you will get a response. Sent me a PM and I will guide you through a different and more user friendly setup.

**Comment by RezzZ** [comment]
> Hi there. I am fairly new to Home assistant and trying to find my way through various setups.
> 
> Am trying to get the ATAG one working. I did the setup and entities now shows the Atag One as climate.atag_one. Copying sensor section into configuration.yaml and restarting however does not add sensor entities. Am I missing a step.

Not to talk this integration down but there is now a supported atag component in ha which does all this integration does. Easy setup via integrations menu

**Comment by pmeij270769** [comment]
Die had ik nog niet gezien.... zal dr eens naar kijken thanx!

M.vr.gr.

Patrick Meijer
Verstuurd vanaf mijn iPhone
