### ISSUE TITLE
Use in energy dashboard

### ISSUE THREAD

**Issue by smuliv** [herikw/home-assistant-custom-components#43]
Hi. Is there any way to use the gas consumtion in energy dashboard?
I searched on Google and many forums but could not find a way to convert the m³/h to something that the energy dashboard accepts.

Thanks
Smuli

**Comment by herikw** [comment]
Hi, 
You may need to create a template sensor like this:

template:
  - sensor:
    - name: "Atag Gasverbruik"
      state: >
        {{ (states ('sensor.atag_one_power_consumption') | float * 0.01) | round(2) }}
      unit_of_measurement: "m³"
      device_class: gas
      state_class: total_increasing

Now you will see "Atag Gasverbruik" in the list. Please note that it takes some time before you will see the first statistics.

**Comment by smuliv** [comment]
Many thanks for your help 😊

Kind regards
