### ISSUE TITLE
Google Home functionality

### ISSUE THREAD

**Issue by reharmsen** [herikw/home-assistant-custom-components#5]
I attached my home assistant to my Google Home.
The thermostat can be seen by my Google Home, but apart from showing/telling the current temperature, I am not able to use it.

Can this be fixed/extended in the component?

**Comment by reharmsen** [comment]
It might be this needs/could be fixed in the Google Assistant component
See: https://github.com/home-assistant/home-assistant/issues/18515

**Comment by reharmsen** [comment]
Or something like this should be implemented:
https://github.com/home-assistant/home-assistant/pull/17892

**Comment by reharmsen** [comment]
It can be fixed by implementing the right Operation Modes.
I created a workaround for my own set-up (https://github.com/reharmsen/home-assistant-custom-components/commit/146e685fca97d9964a58b4049a6fc4eed839334c) in order to get things working.

**Comment by RolfKoenders** [comment]
With the latest version of this Thermostat component im not able to set the thermostat? Does your work around still work @reharmsen ?

**Comment by reharmsen** [comment]
@RolfKoenders 
My version still works

**Comment by reharmsen** [comment]
Seems fixed with climate component rewrite
