### ISSUE TITLE
align names AtagOne / Atag One

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#7]
The thermostat is called Atag One while all sensors use the name AtagOne. Perhaps you can align the thermostat name with the rest?
I already did it locally but just wanted to give the feedback :).

**Comment by herikw** [comment]
Thanks for you comment RezzZ. I aligned the SENSOR_PREFIX with the name of the component.

**Comment by RezzZ** [comment]
@herikw any chance you can remove the space in the default sensor prefix? The climate component is:
`climate.atagone_thermostat` so it would be nice if the sensors also follow this convention (without a space)
