### ISSUE TITLE
Holiday mode not working?

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#8]
Hi, just created an input boolean to turn on holiday mode and disable a few automations but the holiday or vacation mode is not set. It will automatically go back to auto in HA after a few seconds, and in the atag one app I don't see the mode switching either. Shouldn't the holiday mode require a start and end date/time to be set for it to function properly?

**Comment by herikw** [comment]
Hi RezzZ, yes you are right about the holiday mode. It's already in the Operations list. So, no boolean required, but it indeed needs a schedule. I will have a look to see if this can be made available in the user interface.

**Comment by RezzZ** [comment]
with the alignment with general climate components holiday mode is not possible any more
