### ISSUE TITLE
Integrations need to be in their own folder. Change sensor/atagone.py to atagone/sensor.py. This will stop working soon.

### ISSUE THREAD

**Issue by RezzZ** [herikw/home-assistant-custom-components#9]
with the installation of HA 0.89.1 I get the following warning in HA. I think this component need a minor adjustment?
```
Integrations need to be in their own folder. Change sensor/atagone.py to atagone/sensor.py. This will stop working soon.
```
Only thing I miss in the HA documentation is what to do after I move this sensor file to a separate folder. My configuration.yaml should then point to this new folder somehow?

edit: it is actually not working any more in 0.89.1. I can't control the component any more. I reverted back to 0.87.0 for now

**Comment by j360b** [comment]
For climate custom_component I did the following:
1. create folder /config/custom_components/atagone
2. create file climate.py
3. copy atagone.py code in climate.py
4. replace the following lines
old
>from homeassistant.components.climate import (ClimateDevice, PLATFORM_SCHEMA, SUPPORT_TARGET_TEMPERATURE, SUPPORT_OPERATION_MODE)
>from homeassistant.const import (CONF_NAME, CONF_HOST, CONF_PORT, TEMP_CELSIUS, ATTR_TEMPERATURE)

new

>from homeassistant.components.climate import ClimateDevice, PLATFORM_SCHEMA
>from homeassistant.components.climate.const import (
    STATE_COOL, STATE_ECO, STATE_HEAT, STATE_AUTO, SUPPORT_OPERATION_MODE,
    SUPPORT_TARGET_TEMPERATURE, STATE_MANUAL)`

**Comment by QkulleQ** [comment]
Hi @j360bi, I did the steps you described, but unfortunately they didn't work for me.
Clicking:
![atagone-log](https://user-images.githubusercontent.com/48830986/54828334-3b0c5900-4cb4-11e9-8a7b-18ccb7992c48.PNG)
Gives this:
![atagone-errorlog](https://user-images.githubusercontent.com/48830986/54828345-4495c100-4cb4-11e9-8508-1bd386f75be3.PNG)

Hope you can see what's wrong

**Comment by herikw** [comment]
The following line should not be removed from the original source: 
_from homeassistant.const import (CONF_NAME, CONF_HOST, CONF_PORT, TEMP_CELSIUS, ATTR_TEMPERATURE)_
Otherwise you are missing some HA constants.

Btw, you can grab the new version. All changes are incorporated.

**Comment by j360b** [comment]
True, my bad. In my version the line mentioned by @herikw was not removed.. 
Good that there is a new version! Tnx

**Comment by QkulleQ** [comment]
No problem @j360b ! And thanks for the new version @herikw !

**Comment by RezzZ** [comment]
just upgraded the atagone and HA to 0..90.2 and all works again. Thanks @herikw
